set nocompatible
filetype off

execute pathogen#infect()

filetype plugin indent on
syntax enable

"set laststatus=2
"set noshowmode

" Display preferences
set cursorline
set number
set textwidth=78
set wrap

set foldmethod=syntax

set backspace=indent,eol,start
set mouse=a

" Solarized color scheme
set background=dark
colorscheme solarized

" Plugin configuration
let g:EditorConfig_exclude_patterns = ['fugitive://.*']

